### ISSUE TITLE
Same number of votes on two emotions

### ISSUE THREAD

**Issue by xchhuang** [Microsoft/FERPlus#4]
I found that for some images the number of votes on two emotions by the 10 taggers is the same. I wonder how to deal with this problem ?

**Comment by cha-zhang** [comment]
If you use the probabilistic way of training, you should be using the histogram. Otherwise, you can ignore this example. 

Here's the code how we handle such cases when majority mode is used: 
https://github.com/Microsoft/FERPlus/blob/master/src/ferplus.py#L223-L229
