### ISSUE TITLE
How to match the file fer2013new.csv and fer2013

### ISSUE THREAD

**Issue by zhanglaplace** [Microsoft/FERPlus#5]
in the readme, the ferxxxx.png mean the row index of the original fer2013.csv .
but in fer2013new.csv,some lines is empty at the image_name.and how can i 
match the fer2013new and fer2013.csv.

**Comment by ebarsoumMS** [comment]
Hi,

I added generate_training_data.py, which merge fer2013.csv with fer2013new.csv. The empty lines in fer2013new.csv mean ignore the corresponding rows in fer2013.csv. Those are no face images.
